cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

cupons/urls.py
from django.conf.urls import url
from .views import CuponApply

urlpatterns = [
    url(r'^apply', CuponApply, name='apply')
]

demo_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from demo_shop import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.AdminOrderDetail, name='AdminOrderDetail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.AdminOrderPDF, name='AdminOrderPDF')
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views.decorators.http import require_POST

from cart.forms import CartAddProductForm
from shop.models import Product
from .cart import Cart
from cupons.forms import CuponApplyForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    cupon_apply_form = CuponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'cupon_apply_form': cupon_apply_form})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% block title %}
    Ваша корзина товаров
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Ваша корзина товаров</h1><br>
        <table class="table table-bordered table-striped table-cart">
            <thead>
            <tr>
                <th>Иозображение</th>
                <th>Наименование</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена</th>
                <th>Полная цена</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr class="centered">
                        <td><a href="{{ product.get_absolute_url }}"><img style="max-height: 120px"
                                                                          src="{{ product.image.url }}" alt=""/></a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                                {% csrf_token %}
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input type="submit" value="Обновить">
                            </form>
                        </td>
                        <td><a href="{% url "cart:CartRemove" product.id %}" class="btn btn-danger">Удалить</a></td>
                        <td>{{ item.price }} руб.</td>
                        <td>{{ item.total_price }} руб.</td>
                    </tr>

                {% endwith %}
            {% endfor %}


            {% if cart.cupon %}
                <tr class="danger">
                    <td class="text-right" colspan="5">Сумма без скидки</td>
                    <td>{{ cart.get_total_price }}</td>
                </tr>
                <tr class="warning">
                    <td class="text-right" colspan="5">"{{ cart.cupon.cupon_code }}" купон на {{ cart.cupon.discount }} % ниже</td>
                    <td class="num discount">- {{ cart.get_discount|floatformat:"2" }} руб.</td>
                </tr>
            {% endif %}

            <tr class="success">
                <td colspan="5" class="text-right">Итого:</td>
                <td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} руб.</td>
            </tr>
            </tbody>
        </table>
        <form action="{% url "cupon:apply" %}" method="post" class="add">
            {% csrf_token %}
            {{ cupon_apply_form }}
            <input type="submit" class="btn btn-info" value="Активировать купон">
        </form>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="btn btn-success">Продолжить Шопинг</a>
            <a href="{% url "orders:OrderCreate" %}" class="btn btn-success">Оформить заказ</a>
        </p>
    </div>

{% endblock %}