cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

demo_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from demo_shop import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}
<title>
    {% block title %}{% endblock %}
</title>
<body>
{% include 'header.html' %}
<div class="wrap">
    {% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container">
            <div class="copyright text-center">
                <h4>Designed and developed by Marat Nizamutdinov 2017. Все товары и цены выдуманы и не являются реальными.
                </h4>
            </div>
        </div>
    </div>
</div>

templates/head.html
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="магазин">

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo_shop.css' %}"/>
</head>

templates/header.html
{% load staticfiles %}
{% load i18n %}

<div class="navbar navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            </button>
            <a class="navbar-brand" href="{% url 'shop:product_list' %}">Главная</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="navbar-cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <span>В корзине:</span>
                            <span><a href="{% url "cart:CartDetail" %}">
                                {{ total_items }} тов. {{ cart.get_total_price }} руб.
                            </a></span>
                        {% else %}
                            <span>Корзина пустая</span>
                        {% endif %}
                    {% endwith %}
                </li>
            </ul>
        </div>
    </div>
</div>